os: linux
language: python
cache:
    directories:
        - $HOME/.cache/pip

python:
    - 3.7
    - 3.6
    - 3.5

install:
    - pip install numpy
    - pip install -r requirements.txt
    - pip install pytest
    - pip install -e .

script:
    - python --version
    - py.test tests