name: CI

on: [push, pull_request]

jobs:
  src-test:
    name: unit-tests
    runs-on: ubuntu-latest

    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install python dependencies
      run: |
        python -m pip install numpy pytest
        python -m pip install -r requirements.txt
        python --version
        pip --version
        python -m pip list
      shell: bash

    - name: Source code tests
      run: |
        py.test tests