# This is a basic workflow to help you get started with Actions
name: AsteroidMirror

# Controls when the action will run.
on: [push, pull_request]

# A workflow run is made up of one or more jobs
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Clone source repo and push to target
      shell: sh
      run: |
        set -veu
        export SRC_REPO=https://github.com/$GIT_USERNAME/$REPO_NAME
        export TARGET_REPO=https://github.com/asteroid-team/$REPO_NAME
        echo $SRC_REPO to $TARGET_REPO
        git clone --mirror $SRC_REPO
        echo "CD into mirror"
        cd ${REPO_NAME}.git
        echo '#!/bin/sh' > passwd_giver.sh
        echo "exec echo \"\$GIT_PASSWORD\"" >> passwd_giver.sh
        chmod +x passwd_giver.sh
        sh -c "git config --global credential.username $GIT_USERNAME"
        sh -c "git config --global core.askPass ./passwd_giver.sh"
        sh -c "git config --global credential.helper cache"
        sh -c "git remote set-url --push origin $TARGET_REPO"
        sh -c "git fetch -p origin"
        sh -c "git push --mirror"
        sh -c "echo Add other actions to build,"
        sh -c "echo test, and deploy your project."
      env:
        GIT_USERNAME: mpariente
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        REPO_NAME: pytorch_stoi

